### ISSUE TITLE
Client struct to wrap context, config and discovered models

### ISSUE THREAD

**Issue by bikeshedder** [bikeshedder/sunspec#9]
The current API simple enough but having to carry around the context, config and discovered models as separate variables makes it a bit cumbersome to use.

I want to add a `Client` struct:

```rs
pub struct Client {
    pub context: Context,
    pub config: Config,
    pub models: Models,
}
```

Usage of this struct should then look sth. like this:

```rs
let mut client = Client
    .builder()
    .read_timeout(Duration::from_secs(1))
    .build(ctx);
client.discover_models().await?;
let model1 = client.m1().read().await?;
let model103 = client.m103().read().await?;
```

Maybe even get rid of the `discover_models` call and make this part of the build function:

```rs
let mut client = Client
    .builder()
    .read_timeout(Duration::from_secs(1))
    .disover_models(ctx)
    .await?;
let model1 = client.m1().read().await?;
let model103 = client.m103().read().await?;
```

The only issue with that is the need of "bound" model structs which borrow their client:

```rs
impl AsyncSunspecClient for Client {
    async fn m1(&mut self) -> BoundModelAddr<Model1> {
        BoundModelAddr(self, self.models.m1)
    }
    // ...
}
```

I'm not too happy about needing this `BoundModelAddr` wrapper though and having to call a `m1()` function to borrow `self` and return it isn't pretty either.

A bit less clever, easier to maintain – maybe even more use friendly is the use of a generic parameter to the `read_/write_model` functions:

```rs
let model1 = client.read_model::<Model1>().await?;
let model103 = client.read_model::<Model103>().await?;
```

The only thing I don't like about that is the need of the turbofish (`::<>`) syntax.

As one can also type the LHS it's probably a non-issue anyways:

```rs
let model1: Model1 = client.read_model().await?;
let model103: Model103 = client.read_model().await?;
```

While at it I also want to tackle the Error enums and replace the `dyn Error` by a concrete type. The initial discussion and PR can be found here:

- #7

**Comment by jacobsvante** [comment]
Yes please to interface improvements! Would this involve `write_point` as well?

Personally I don't mind the turbofish syntax or LHS type declaration. Deserializing with Serde involves the same procedure.

Another feature I'd like to request is adding an enum containing all the model names, and a way to go from those to the actual models. I had the need for this when creating a CLI for quickly firing off requests. As you can see in my example below it's quite cumbersome as of today:

```rust
#[derive(Debug, Clone, Copy, ValueEnum)]
pub(crate) enum SunspecModel {
    M1,
    M2,
    M3,
}

impl SunspecModel {
    async fn read(
        &self,
        ctx: &mut Context,
        models: &mut Models,
    ) -> Result<Box<dyn std::fmt::Debug>> {
        let config = sunspec::Config::default();
        match self {
            SunspecModel::M1 => Ok(Box::new(read_model(ctx, &models.m1, &config).await?)),
            SunspecModel::M2 => Ok(Box::new(read_model(ctx, &models.m2, &config).await?)),
            SunspecModel::M3 => Ok(Box::new(read_model(ctx, &models.m3, &config).await?)),
        }
    }
}
```

**Comment by bikeshedder** [comment]
> Yes please to interface improvements! Would this involve write_point as well?

It would also involve changes to `write_point`. As of now it's quite cumbersome having to pass a context, model address, point, value and config. I'm hoping to reduce this to a more sane API such as:

```rs
client.write_point::<Model1::DA>(Some(42));
```

Writing to nested and repeating groups that way isn't possible though and I wonder if it really is the best API for that operation.

> Another feature I'd like to request (...)

I've created a new tracking issue for that feature request:

- #11

**Comment by jacobsvante** [comment]
> I'm hoping to reduce this to a more sane API such as:
> 
> ```rust
> client.write_point::<Model1::DA>(Some(42))
> ```

Oh, I like the look of that!

> Writing to nested and repeating groups that way isn't possible though and I wonder if it really is the best API for that operation.

Hmm I've never had to write to nested or repeating groups, is that a common thing? I noticed you have issue #3 relating to this. Personally I find it easier to implement APIs for things I can test real life cases with, and then rewrite if/when the need comes. As long as `sunspec` is not 1.0 you have the freedom 😉

> > Another feature I'd like to request (...)
> 
> I've created a new tracking issue for that feature request:
> 
>     * [Add a list of models to the generated code #11](https://github.com/bikeshedder/sunspec/issues/11)

Thanks! I was thinking it might be relevant to the new API design, but maybe it's not.

**Comment by bikeshedder** [comment]
> Hmm I've never had to write to nested or repeating groups, is that a common thing? (...)

I don't have any need for this at the moment. I just would like have a fully spec compliant library so I can call it a `1.0`.

tbh. I only started this crate as I was curious to learn more about my 3 phase inverter and integrated it into my smart home system with this very simple code: https://github.com/bikeshedder/nrg/blob/main/nrg-sunspec/src/main.rs

Writing a code generator for full model validation and a nice API really wasn't necessary. I could just have made a few modbus calls and call it the day. I kind of overshoot here ... a bit. :rofl:

I just love good software engineering. That's why I'm doing this to begin with.

**Comment by bikeshedder** [comment]
Let's move this discussion to Discord. You can find me as @bikeshedder on the Tokio and Rust servers. Or write me directly:

- https://discordapp.com/users/288231469854228483
